// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niqnhnallagcabxpeckx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pcW5obmFsbGFnY2FieHBlY2t4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTE5NjUsImV4cCI6MjA2MzI2Nzk2NX0.eJnacEIoqyEloeTrxI1nhb6D6vaPmSESoElMPo23o94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);